name: ManagerApp
options:
  bundleIdPrefix: com.rentalhelper
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

packages:
  StockBnBShared:
    path: ../StockBnBShared

targets:
  ManagerApp:
    type: application
    platform: iOS
    sources:
      - ManagerApp
    dependencies:
      - package: StockBnBShared
    settings:
      base:
        INFOPLIST_FILE: ManagerApp/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.rentalhelper.manager
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    info:
      path: ManagerApp/Resources/Info.plist
      properties:
        CFBundleDisplayName: Rental Helper Manager
        CFBundleName: ManagerApp
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        ITSAppUsesNonExemptEncryption: false
