name: CleanerApp
options:
  bundleIdPrefix: com.rentalhelper
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

packages:
  StockBnBShared:
    path: ../StockBnBShared

targets:
  CleanerApp:
    type: application
    platform: iOS
    sources:
      - CleanerApp
    dependencies:
      - package: StockBnBShared
    settings:
      base:
        INFOPLIST_FILE: CleanerApp/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.rentalhelper.cleaner
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    info:
      path: CleanerApp/Resources/Info.plist
      properties:
        CFBundleDisplayName: Rental Helper
        CFBundleName: CleanerApp
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        ITSAppUsesNonExemptEncryption: false
        NSCameraUsageDescription: "Rental Helper needs camera access to count inventory items using AI"
        NSPhotoLibraryUsageDescription: "Rental Helper needs photo library access to select images for AI counting"
